routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CostumersController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CostumerRegistriController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\Ecommerce\FrontController;
use App\Http\Controllers\Ecommerce\CartController;
use App\Http\Controllers\Ecommerce\OrderController as EcommerceOrderController;
use App\Http\Controllers\OrderController;
use App\Models\OrderDetail;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [FrontController::class, 'index'])->name('front.index');
Route::get('/produk', [FrontController::class, 'product'])->name('front.product');
Route::get('/category/{slug}', [FrontController::class,'categoryProduct'])->name('front.category');
Route::get('/product/{slug}', [FrontController::class, 'show'])->name('front.show_product');
Route::get('/contact', function () {
    return view('costumer.contact');
});

Route::get('/coba', function () {
    return view('costumer.cart');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

Route::group(['middleware' => ['auth']], function () {

    /* route product */
    Route::get('auth/product', [ProductController::class, 'index'])->name('product.index');
    Route::get('create/product', [ProductController::class, 'create'])->name('product.create');
    Route::post('create/product', [ProductController::class, 'store'])->name('product.store');
    Route::get('product/{product_id}/edit', [ProductController::class, 'edit'])->name('product.edit');
    Route::put('product/{product_id}', [ProductController::class, 'update'])->name('product.update');
    Route::delete('product/{product_id}', [ProductController::class, 'destroy'])->name('product.destroy');

    Route::get('product/bulk', [ProductController::class, 'massUploadForm'])->name('product.bulk');
    Route::post('product/bulk', [ProductController::class, 'massUpload'])->name('product.saveBulk');

    /* route kategori */
    Route::get('kategori', [CategoryController::class, 'index'])->name('category.index');
    Route::post('kategori', [CategoryController::class, 'store'])->name('category.store');
    Route::get('kategori/{category_id}/edit', [CategoryController::class, 'edit'])->name('category.edit');
    Route::put('kategori/{category_id}', [CategoryController::class, 'update'])->name('category.update');
    Route::delete('kategori/{category_id}', [CategoryController::class, 'destroy'])->name('category.destroy');

    /* Order */
    Route::get('order/index', [OrderController::class, 'index'])->name('order.index');
    Route::post('order/update/{id}', [OrderController::class, 'update'])->name('order.update');
    Route::delete('order/destroy/{id}', [OrderController::class, 'destroy'])->name('order.destroy');
    Route::get('order', [OrderController::class, 'viewOrder'])->name('report.order');
    Route::get('order/pdf/{daterange}', [OrderController::class, 'orderReportPdf'])->name('report.order_pdf');
});


/* costumer login & register */
Route::prefix('/costumer')->name('costumer.')->namespace('Costumer')->group(function(){
    Route::get('/login', [CostumersController::class, 'showLoginForm'])->name('login');
    Route::post('/login', [CostumersController::class, 'login'])->name('login.post');
    Route::post('/logout', [CostumersController::class, 'logout'])->name('logout');
    Route::get('/register', [CostumerRegistriController::class, 'showRegisterForm'])->name('register');
    Route::post('/register', [CostumerRegistriController::class, 'createCostumer'])->name('register.post');
});



/* costumer after login */
Route::group(['middelware' => 'costumer'], function () {
    Route::get('/costumer/home', [HomeController::class, 'index'])->name('home.index');
    Route::get('/costumer/produk', [HomeController::class, 'product'])->name('home.product');
    Route::get('/costumer/category/{slug}', [HomeController::class,'categoryProduct'])->name('home.category');
    Route::get('/costumer/product/{slug}', [HomeController::class, 'show'])->name('home.show_product');

    Route::get('/costumer/cart', [CartController::class, 'index'])->name('home.list_cart');
    Route::get('/costumer/checkout', [EcommerceOrderController::class, 'checkout'])->name('home.checkout');
    Route::post('/costumer/checkout', [EcommerceOrderController::class, 'processCheckout'])->name('home.checkoutproses');
    // Route::post('/costumer/ongkir', [CartController::class, 'check_ongkir'])->name('home.cekongkir');
    Route::post('/costumer/cartadd', [CartController::class, 'addToCart'])->name('home.addcart');
    Route::patch('/costumer/cartupdate/{cart}', [CartController::class, 'updateCart'])->name('home.update_cart');
    Route::delete('/costumert/cart/delete/{id}', [CartController::class, 'destroy']);

    Route::get('/costumer/order/{invoice}', [EcommerceOrderController::class, 'index'])->name('home.order');
    Route::get('/costumer/order-detail', [EcommerceOrderController::class, 'detail'])->name('home.orderdetail');
    Route::get('/costumer/payment/{invoice}', [EcommerceOrderController::class, 'paymentForm'])->name('home.payment-form');
    Route::post('/costumer/payment/{invoice}', [EcommerceOrderController::class, 'payment'])->name('home.payment');
    Route::post('/costummer/order/update/{id}', [EcommerceOrderController::class, 'update'])->name('home.order.update');
    Route::get('/costumer/pdf/{id}', [EcommerceOrderController::class, 'generatepdf'])->name('home.pdf');

    // Route::get('/costumer/create', [CartController::class, 'coba'])->name('home.coba');

    Route::get('/cities/{id}', [CartController::class, 'getCity']);

});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700" rel="stylesheet">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        @livewireStyles

        <!-- Scripts -->
        <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.6.0/dist/alpine.js" defer></script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @livewire('navigation-dropdown')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>

        @stack('modals')

        @livewireScripts
    </body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700" rel="stylesheet">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.2.1/dist/alpine.js" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <title>Candy Store - @yield('title')</title>
    {{-- <link rel="icon" href="img/Fevicon.png" type="image/png"> --}}
  <link rel="stylesheet" href="{{asset("assets/vendors/bootstrap/bootstrap.min.css")}}">
  <link rel="stylesheet" href="{{asset("assets/vendors/fontawesome/css/all.min.css")}}">
  <link rel="stylesheet" href="{{asset("assets/vendors/themify-icons/themify-icons.css")}}">
  <link rel="stylesheet" href="{{asset("assets/vendors/nice-select/nice-select.css")}}">
  <link rel="stylesheet" href="{{asset("assets/vendors/owl-carousel/owl.theme.default.min.css")}}">
  <link rel="stylesheet" href="{{asset("assets/vendors/owl-carousel/owl.carousel.min.css")}}">

  @yield('css')

  <link rel="stylesheet" href="{{asset("assets/css/style.css")}}">
</head>
<body>
  <!--================ Start Header Menu Area =================-->
  <header class="header_area">
    <div class="main_menu">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand logo_h" href="index.html"><img src="img/logo.png" alt=""></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
            <ul class="nav navbar-nav menu_nav ml-auto mr-auto">
            @if(Auth::guard('costumer')->check())
              <li class="nav-item @yield('index')"><a class="nav-link" href="{{ route('home.index') }}">Home</a></li>
              <li class="nav-item @yield('produk')"><a class="nav-link" href="{{ route('home.product') }}">Produk</a></li>
            @else
                <li class="nav-item @yield('index')"><a class="nav-link" href="{{ route('front.index') }}">Home</a></li>
                <li class="nav-item @yield('produk')"><a class="nav-link" href="{{ route('front.product') }}">Produk</a></li>
            @endif
            </ul>

            <ul class="nav-shop">

              @if(Auth::guard('costumer')->check())
                    <li class="nav-item"><button><a href=" {{route('home.orderdetail')}} "><i class="ti-list"></i></a></button></li>
                    <li class="nav-item"><button><a href=" {{route('home.list_cart')}} "><i class="ti-shopping-cart"></i></a><span class="nav-shop__circle"> {{$cart->count()}} </span></button> </li>

                    <li class="nav-item submenu dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                          aria-expanded="false">{{ Auth::guard('costumer')->user()->name }}</a>
                          <form method="POST" action="{{ route('logout') }}">
                            @csrf
                            <ul class="dropdown-menu">
                                <li class="nav-item"><a class="nav-link" href="{{ route('costumer.logout') }}" onclick="event.preventDefault();
                                    this.closest('form').submit();"> {{ __('Logout') }}</a></li>
                            </ul>
                          </form>
                    </li>
                </div>
            @else
                <li class="nav-item"><button><i class="ti-list"></i></button></li>
                <li class="nav-item"><button><i class="ti-shopping-cart"></i></a></span></button> </li>
                <li class="nav-item"><a class="button button-header" href="{{ route('costumer.login') }}">Login</a></li>
            @endif
            </ul>
          </div>
        </div>
      </nav>
    </div>
  </header>
	<!--================ End Header Menu Area =================-->
  @yield('section-login')

  @yield('main')


  <!--================ Start footer Area  =================-->
	<footer class="footer">
		<div class="footer-area">
			<div class="container">
				<div class="row section_gap">
					<div class="col-lg-3 col-md-6 col-sm-6">
						<div class="single-footer-widget tp_widgets">
							<h4 class="footer_title large_title">Our Mission</h4>
							<p>
								Menyediakan buku dengan aneka ragam dengan lengkap yang akan sesuai dengan masing masing pelanggan
							</p>
						
						</div>
					</div>
					<div class="offset-lg-1 col-lg-2 col-md-6 col-sm-6">
						<div class="single-footer-widget tp_widgets">
							<h4 class="footer_title">Quick Links</h4>
							<ul class="list">
								<li><a href="{{ route('home.index') }}">Home</a></li>
								<li><a href="{{ route('home.product') }}">Produk</a></li>
								<li><a href="#">Kontak</a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-2 col-md-6 col-sm-6">
						<div class="single-footer-widget instafeed">
							<h4 class="footer_title">Gallery</h4>
							<ul class="list instafeed d-flex flex-wrap">
                  @foreach ($products as $row)
                      <li><img src="{{ asset('storage/products/' . $row->image) }}" class="img-fluid" style="height: 70px;" alt=" {{$row->name}} "></li>
                  @endforeach
							</ul>
						</div>
					</div>
					<div class="offset-lg-1 col-lg-3 col-md-6 col-sm-6">
						<div class="single-footer-widget tp_widgets">
							<h4 class="footer_title">Contact Us</h4>
							<div class="ml-40">

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="footer-bottom">
			<div class="container">
				<div class="row d-flex">
					<p class="col-lg-12 footer-text text-center">
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
				</div>
			</div>
		</div>
	</footer>
	<!--================ End footer Area  =================-->



  <script src="{{asset('assets/vendors/jquery/jquery-3.2.1.min.js')}}"></script>
  <script src="{{asset('assets/vendors/skrollr.min.js')}}"></script>
  <script src="{{asset('assets/vendors/owl-carousel/owl.carousel.min.js')}}"></script>
  <script src="{{asset('assets/vendors/jquery.ajaxchimp.min.js')}}"></script>
  <script src="{{asset('assets/vendors/mail-script.js')}}"></script>
  <script src="{{asset('assets/vendors/bootstrap/bootstrap.bundle.min.js')}}"></script>
  <script src="{{asset('assets/js/main.js')}}"></script>

  @yield('js')
</body>
</html>